# Identificadores del proyecto
sonar.projectKey=hospital_api
sonar.projectName=Hospital API - Proyecto P1
sonar.projectVersion=2.0.0

# Directorio base para el análisis (la raíz del proyecto)
sonar.sources=src,client/src
sonar.tests=test,client/src
sonar.test.inclusions=test/**/*.test.js,client/src/**/*.spec.ts

# 🚨 EL FILTRO CRÍTICO: Exclusiones estrictas
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,client/src/**/*.spec.ts

# (Opcional) Vincular el reporte de cobertura de Jest si lo necesitas
sonar.javascript.lcov.reportPaths=coverage/lcov.info,client/coverage/lcov.info
sonar.typescript.lcov.reportPaths=client/coverage/lcov.info
sonar.coverage.exclusions=src/database/**,api/**,scripts/**
sonar.qualitygate.wait=true
